# Mutant class example

from pyviko.mutation import Mutant

sequence = '''ATGGAACAGGCACCAGAAGATCAAGGACCACAGAGGGAGCCATACAACGAATGGGCTTTAGAATTGTTGGAAGACCTAAAGAATGAGGCTCTGCGCCACTTTCCTCGGCCTTGGCTACATGGACTAGGGCAATACTTCTATAATACATATGGAGATACCTGGGAGGGAGTAGAGGCCATCATTAGGACACTACAACAACTGTTGTTTATACATTATAGGATTGGCTGTCAACATAGCAGGATAGGAATCACTCCTCAAAGGAGAAGGAATGGAGCCAGTAGATCCTGA'''

mut_seq = Mutant(sequence)
mutants = mut_seq.find_mutants(ignore_rx_sites = False)
write_mutant_fasta_bio('test_mutations.fasta', SeqRecord(sequence, id = "TestSeq"))
